name: Build & Deploy Android

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build & Create Unsigned Artifacts
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
        
      - name: Install Cordova
        run: npm install -g cordova
        
      - name: Install Cordova Resources Plugin
        run: sudo npm install -g --unsafe-perm cordova-res
          
      - name: Install Dependencies
        run: npm ci
        
      #- name: Cordova - Generate Resources
      #  run: cordova-res android
        
      - name: Cordova - Platform Add Android
        run: cordova platform add android

      - name: Cordova - Build Debug
        run: cordova build android --debug
      
      - name: Upload Debug Artifact
        uses: actions/upload-artifact@v2
        with:
          name: App - Debug
          path: platforms/android/app/build/outputs/apk/debug/app-debug.apk

      - name: Cordova - Build Release
        run: cordova build android --release
      
      - name: Upload Release Artifact
        uses: actions/upload-artifact@v2
        with:
          name: App - Release Usigned
          path: platforms/android/app/build/outputs/apk/release/app-release-unsigned.apk
  
  sign-deploy:
    name: Signing & Deploy to Play Store
    runs-on: macos-latest
    needs: [build]
    
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: App - Release Usigned
          path: signing
      
      - name: Signing with Keystore from Secrets
        uses: thomastvedt/sign-android-release@v2.2
        with:
          releaseDirectory: signing
          signingKeyBase64: ${{ secrets.KEYSTORE_BASE64 }}
          keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
          alias: ${{ secrets.KEY_NAME }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
          
      - name: Rename signed .apk-Files
        run: |
          ls -R
          mv signing/app-release-unsigned-aligned.apk signing/app-release-aligned.apk
          mv signing/app-release-unsigned-signed.apk signing/app-release-signed.apk
      
      - name: Upload Release Artifact
        uses: actions/upload-artifact@v2
        with:
          name: App - Release Signed
          path: signing/app-release-signed.apk
          
      - name: List
        run: ls -R
      
      - uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT }}
          packageName: fyi.jakob.cordovaGithubBuildAndDeploy
          releaseFile: ./signing/app-release-signed.apk
          track: internal
        # whatsNewDirectory: ./docs/whatsnew/
        # mappingFile: app/build/outputs/mapping/release/mapping.txt
